services:
  api:
    build:
      context: .
      dockerfile: code/backend/Dockerfile.api
    container_name: model_api
    ports:
      - "8000:8000"

  app:
    build:
      context: .
      dockerfile: code/frontend/Dockerfile.front
    container_name: front_api
    ports:
      - "8501:8501"
    depends_on:
      - api