FROM python:3.11-slim

WORKDIR /app

RUN pip install uv

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --group frontend

COPY code/frontend ./app

CMD ["uv", "run", "streamlit", "run", "app/streamlit.py", "--server.port=8501", "--server.address=0.0.0.0"]